image: docker:stable

stages:
  - build
  - release
  - deploy
    
variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  COMPOSE_PROJECT_NAME: photon-bot
  
before_script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo $SSH_AGENT_PID > /tmp/agent-${CI_JOB_ID}
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ls ~/.ssh || mkdir ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

after_script:
  - SSH_AGENT_PID=$(cat /tmp/agent-${CI_JOB_ID}) ssh-agent -k

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

release-image:
  stage: release
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy-master:
  variables:
    DOCKER_HOST: ssh://$FTP_USER@$FTP_HOST
    GIT_STRATEGY: none
    DOCKER_NAME: photon-bot
    DOCKER_IMG_VERSION: latest
  stage: deploy
  script:
    - scp $FTP_USER@$FTP_HOST:~/env/"$DOCKER_NAME" .env
    - docker-compose up -d --build
  only:
    - master
  environment:
    name: production

deploy-dev:
  variables:
    DOCKER_HOST: "ssh://$FTP_USER@$FTP_HOST"
    DOCKER_NAME: photon-bot-dev
    DOCKER_IMG_VERSION: $CI_COMMIT_REF_SLUG
  stage: deploy
  script:
      - scp $FTP_USER@$FTP_HOST:~/env/"$DOCKER_NAME" .env
      - docker-compose up -d --build
  environment:
    name: development
  except:
    - master