version: "3"

volumes:
  faktory:
  photon:
  database:

services:
  queue:
    image: contribsys/faktory
    volumes:
      - "faktory:/var/lib/faktory"
    ports:
      - "127.0.0.1:7420:7420"
    env_file:
      - .env
    restart: always
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "7422:3306"
  bot:
#    build: bot
    image: docker.pkg.github.com/photonle/bot/discord:${DOCKER_IMG_VERSION}
    env_file:
      - .env
    volumes:
      - "photon:/app"
    restart: always
    depends_on:
      - queue
      - db
  worker:
#    build: worker
    image: docker.pkg.github.com/photonle/bot/runner:${DOCKER_IMG_VERSION}
    env_file:
      - .env
    depends_on:
      - queue
      - db
    restart: always
  adminer:
      image: adminer
      restart: always
      ports:
        - "127.0.0.1:7421:8080"
      depends_on:
        - db
