version: "3"

volumes:
  faktory:
  photon:

services:
  queue:
    image: contribsys/faktory
    volumes:
      - "faktory:/var/lib/faktory"
    ports:
      - "127.0.0.1:7420:7420"
    env_file:
      - .env
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
  bot:
    image: registry.git.doctor-internet.dev/photon/discord-bot
    depends_on:
      - queue
    env_file:
      - .env
    volumes:
      - "photon:/app"
  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - queue
