name: Bot Deployment
on:
  push:
    paths:
      - bot/**
      - .github/workflows/deploy-bot.yml
      - docker-compose.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Setup Tools
        run: sudo apt-get install python3-setuptools
      - name: Update Docker-Compose
        run: sudo pip3 install docker-compose
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Key
        uses: shimataro/ssh-key-action@v1.3.0
        with:
          private-key: ${{ secrets.SSH_KEY }}
          known-hosts: 51.68.207.67 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJaetLRp2rtHETI3eO6Wk9UgWfsiIYHu/Uvi54lHlR8l
      - name: Deploy
        env:
          DOCKER_HOST: ssh://${{ secrets.FTP_USER }}@51.68.207.67
          DOCKER_NAME: photon-bot
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_HOST: 51.68.207.67
          COMPOSE_PROJECT_NAME: photon-bot
        run: |
          scp $FTP_USER@$FTP_HOST:~/env/"$DOCKER_NAME" .env
          docker context create remote --docker "host=$DOCKER_HOST"
          docker-compose --context remote up -d --build worker
