name: Worker Deployment
on:
  push:
    paths:
      - worker/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker-Compose
        run: sudo pip install docker-compose
      - uses: actions/checkout@master
      - name: Build & Publish Image
        uses: elgohr/Publish-Docker-Github-Action@2.7
        with:
          name: ${{ github.repository }}/worker
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_semver: true
          snapshot: true
          workdir: worker
      - name: Install Key
        uses: shimataro/ssh-key-action@v1.3.0
        with:
          private-key: ${{ secrets.SSH_KEY }}
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy
        env:
          DOCKER_HOST: ssh://${{ secrets.FTP_USER }}@git.doctor-internet.dev
          DOCKER_IMG_VERSION: latest
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_HOST: git.doctor-internet.dev
          COMPOSE_PROJECT_NAME: photon-bot
        run: |
          scp $FTP_USER@$FTP_HOST:~/env-"$DOCKER_NAME" .env
          docker-compose --version
          docker-compose up -d worker
